# Generated by Django 3.2.8 on 2022-01-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
