# Generated by Django 3.2.8 on 2022-01-14 06:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 14, 6, 46, 28, 484873, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
