# Generated by Django 3.2.8 on 2022-01-20 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_todo_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='author',
        ),
    ]
